<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb826f45a7709ca1fad107b8c7dcff8f7
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb826f45a7709ca1fad107b8c7dcff8f7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb826f45a7709ca1fad107b8c7dcff8f7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb826f45a7709ca1fad107b8c7dcff8f7::$classMap;

        }, null, ClassLoader::class);
    }
}
